services:
  lpa-dashboard:
    image: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/sirius/sirius-lpa-dashboard:latest
    build:
      dockerfile: docker/sirius-lpa-dashboard/Dockerfile
    depends_on:
      - sirius-mock
    ports: ["8888:8888"]
    privileged: false
    user: app
    read_only: true
    environment:
      PORT: 8888
      HEALTHCHECK: /lpa/dashboard/health-check
      SIRIUS_URL: http://sirius-mock:8080
      SIRIUS_PUBLIC_URL: http://localhost:8080

  sirius-mock:
    image: wiremock/wiremock:3.13.2@sha256:fd27e46090916e85326229e5102ee169ae729059f3374549615bd20a35fee1f2
    ports: ["8563:8080"]
    volumes:
      - "./cypress/mocks:/home/wiremock/mappings"

  puppeteer:
    build: docker/puppeteer
    depends_on:
      - lpa-dashboard
    environment:
      - LHCI_BUILD_CONTEXT__CURRENT_HASH=$GITHUB_SHA
      - LHCI_BUILD_CONTEXT__GITHUB_REPO_SLUG=ministryofjustice/opg-sirius-lpa-dashboard
      - LHCI_GITHUB_APP_TOKEN

  go-lint:
    image: golangci/golangci-lint:v2.12.2@sha256:5cceeef04e53efe1470638d4b4b4f5ceefd574955ab3941b2d9a68a8c9ad5240
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
      - ./.cache/golangci-lint/v1.53.3:/root/.cache
    command: golangci-lint run -v --timeout 5m --enable gosec --output.text.path stdout --output.sarif.path test-results/golangci-lint.sarif

  test-runner:
    build:
      context: docker/test-runner/
    command: gotestsum --junitfile test-results/unit-tests.xml -- ./... -coverprofile=test-results/test-coverage.txt
    working_dir: /go/src/app
    volumes:
      - ./:/go/src/app
      - ./.gocache:/go/pkg/mod

  pact:
    image: pactfoundation/pact-cli:1@sha256:cd239d7b1665263ac30d2d1b411238dff783ce2b547ddcec51ab460555371cca
    working_dir: /go/src/app
    volumes:
      - ./pacts:/go/src/app/pacts

  cypress:
    image: cypress/included:15.21.0@sha256:af15ca5f3b851e32360f37e1d446d6e6821fd11928c87a2fd7fad12e8495e63b
    command: run --browser chrome
    entrypoint: cypress
    depends_on:
      - lpa-dashboard
      - sirius-mock
    environment:
      - CYPRESS_BASE_URL=http://lpa-dashboard:8888
      - CYPRESS_MOCK_SERVER_URI=http://sirius-mock:8080
      - CYPRESS_VIDEO=false
    working_dir: /e2e
    volumes:
      - ./:/e2e
