name: Generate scan report

on:
  push:
    branches:
      - "main"
  schedule:
    # Every thursday, at 12:20 UTC
    - cron: '20 12 * * 4'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ministryofjustice/opg-repository-scanner@latest
